services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    environment:
      - PORT=3002
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=lcdamy
      - DB_PASSWORD=Zudanga@1
      - DB_NAME=qt_challenge_3
      - JWT_SECRET=secret
      - JWT_SECRET_REFRESH=secret_refresh
      - FRONTEND_URL=http://localhost:3001
    networks:
      - qt_network

  mysql:
    image: mysql:latest
    platform: linux/x86_64
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Zudanga@1
      - MYSQL_DATABASE=qt_challenge_3
      - MYSQL_USER=lcdamy
      - MYSQL_PASSWORD=Zudanga@1
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - qt_network

  frontend:
    build:
      context: ../qt_challenge_frontend
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - NEXTAUTH_SECRET=secret
      - NEXTAUTH_URL=http://localhost:3001
      - NEXT_PUBLIC_API_URL=http://localhost:3002
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3001
      - NEXT_PUBLIC_DEFAULT_PASSWORD=123456789
    networks:
      - qt_network

volumes:
  mysql_data:

networks:
  qt_network: