# fly.toml app configuration file generated for qt-challenge-backend-api on 2025-03-10T08:44:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'qt-challenge-backend-api'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
