name: run-api-ci-cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install packages
        run: npm install

      - name: build docker image
        run: docker build -t lcdamy/qt-challenge-backend-api:1.0 ./

      - name: log in to DockerHub
        run: echo ${{ secrets.DOCKER_SECRET }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: push docker image to dockerhub
        run: docker push lcdamy/qt-challenge-backend-api:1.0

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 'HRKU-dcd2a746-8732-4185-b7b2-a1abf1a1d8eb'
          heroku_app_name: 'qt-challenge'
          heroku_email: 'zudanga@gmail.com'

